<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>PoslovnaLogika</RootNamespace>
    <AssemblyName>PoslovnaLogika</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1_SlojPodataka\KlasePodataka\KlasePodataka.csproj" />
  </ItemGroup>

</Project>
